//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientValidations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientValidations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModels.Resources.ClientValidations", typeof(ClientValidations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added on Email.
        /// </summary>
        public static string AddedOnEmail_Display {
            get {
                return ResourceManager.GetString("AddedOnEmail_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added on Skype.
        /// </summary>
        public static string AddedOnSkype_Display {
            get {
                return ResourceManager.GetString("AddedOnSkype_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Full Address.
        /// </summary>
        public static string ClientAddress_Display {
            get {
                return ResourceManager.GetString("ClientAddress_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Company Email Address.
        /// </summary>
        public static string ClientCompanyEmailID_Display {
            get {
                return ResourceManager.GetString("ClientCompanyEmailID_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Company Name.
        /// </summary>
        public static string ClientCompanyName_Display {
            get {
                return ResourceManager.GetString("ClientCompanyName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Company Website.
        /// </summary>
        public static string ClientCompanyWebsite_Display {
            get {
                return ResourceManager.GetString("ClientCompanyWebsite_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Country.
        /// </summary>
        public static string ClientCountry_Display {
            get {
                return ResourceManager.GetString("ClientCountry_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string ClientEmailID_Display {
            get {
                return ResourceManager.GetString("ClientEmailID_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Email Address..
        /// </summary>
        public static string ClientEmailID_Invalid {
            get {
                return ResourceManager.GetString("ClientEmailID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string ClientName_Display {
            get {
                return ResourceManager.GetString("ClientName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Client Name..
        /// </summary>
        public static string ClientName_Required {
            get {
                return ResourceManager.GetString("ClientName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Skype ID.
        /// </summary>
        public static string ClientSkypeID_Display {
            get {
                return ResourceManager.GetString("ClientSkypeID_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNo_Display {
            get {
                return ResourceManager.GetString("ContactNo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_Display {
            get {
                return ResourceManager.GetString("Description_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time Hired on Upwork ID.
        /// </summary>
        public static string FirstHiredUpworkID_Display {
            get {
                return ResourceManager.GetString("FirstHiredUpworkID_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Number.
        /// </summary>
        public static string GSTNo_Display {
            get {
                return ResourceManager.GetString("GSTNo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired By.
        /// </summary>
        public static string HiredBy_Display {
            get {
                return ResourceManager.GetString("HiredBy_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time Hiring Date.
        /// </summary>
        public static string HiringDate_Display {
            get {
                return ResourceManager.GetString("HiringDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Number.
        /// </summary>
        public static string PANNo_Display {
            get {
                return ResourceManager.GetString("PANNo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal Address.
        /// </summary>
        public static string PaypalAddress_Display {
            get {
                return ResourceManager.GetString("PaypalAddress_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string ProfileImage_Display {
            get {
                return ResourceManager.GetString("ProfileImage_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference By Contact Number.
        /// </summary>
        public static string ReferenceByContactNo_Display {
            get {
                return ResourceManager.GetString("ReferenceByContactNo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference By Email Or Skype.
        /// </summary>
        public static string ReferenceByEmailSkype_Display {
            get {
                return ResourceManager.GetString("ReferenceByEmailSkype_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference By Name.
        /// </summary>
        public static string ReferenceByName_Display {
            get {
                return ResourceManager.GetString("ReferenceByName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string TaxNo_Display {
            get {
                return ResourceManager.GetString("TaxNo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Time Zone.
        /// </summary>
        public static string TimeZone_Display {
            get {
                return ResourceManager.GetString("TimeZone_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp Number.
        /// </summary>
        public static string WhatsappNo_Display {
            get {
                return ResourceManager.GetString("WhatsappNo_Display", resourceCulture);
            }
        }
    }
}
