//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeValidations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeValidations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModels.Resources.EmployeeValidations", typeof(EmployeeValidations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhar Card Number.
        /// </summary>
        public static string AadharNumber_Display {
            get {
                return ResourceManager.GetString("AadharNumber_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNo_Display {
            get {
                return ResourceManager.GetString("ContactNo_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address should be only of domain: &quot;webastral.com&quot;.
        /// </summary>
        public static string DomainEmailCheck_Invalid {
            get {
                return ResourceManager.GetString("DomainEmailCheck_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string EmpDOB_Display {
            get {
                return ResourceManager.GetString("EmpDOB_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        public static string EmpEmailID_AlreadyExists {
            get {
                return ResourceManager.GetString("EmpEmailID_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string EmpEmailID_Display {
            get {
                return ResourceManager.GetString("EmpEmailID_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Email Address..
        /// </summary>
        public static string EmpEmailID_Invalid {
            get {
                return ResourceManager.GetString("EmpEmailID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email ID..
        /// </summary>
        public static string EmpEmailID_Required {
            get {
                return ResourceManager.GetString("EmpEmailID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Father Name.
        /// </summary>
        public static string EmpFatherName_Display {
            get {
                return ResourceManager.GetString("EmpFatherName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string EmpFullName_Display {
            get {
                return ResourceManager.GetString("EmpFullName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Full Name..
        /// </summary>
        public static string EmpFullName_Required {
            get {
                return ResourceManager.GetString("EmpFullName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Mother Name.
        /// </summary>
        public static string EmpMotherName_Display {
            get {
                return ResourceManager.GetString("EmpMotherName_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Email ID.
        /// </summary>
        public static string EmpPersonalEmailID_Display {
            get {
                return ResourceManager.GetString("EmpPersonalEmailID_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Joining.
        /// </summary>
        public static string JoiningDate_Display {
            get {
                return ResourceManager.GetString("JoiningDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Drawn Salary on Relieving.
        /// </summary>
        public static string LastDrawnSalary_Display {
            get {
                return ResourceManager.GetString("LastDrawnSalary_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Drawn Salary must be integer.
        /// </summary>
        public static string LastDrawnSalary_ValidInteger {
            get {
                return ResourceManager.GetString("LastDrawnSalary_ValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Address.
        /// </summary>
        public static string LocalAddress_Display {
            get {
                return ResourceManager.GetString("LocalAddress_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype ID.
        /// </summary>
        public static string OfficialSkype_Display {
            get {
                return ResourceManager.GetString("OfficialSkype_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Card Number.
        /// </summary>
        public static string PANNumber_Display {
            get {
                return ResourceManager.GetString("PANNumber_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Address.
        /// </summary>
        public static string PermanentAddress_Display {
            get {
                return ResourceManager.GetString("PermanentAddress_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Skype ID.
        /// </summary>
        public static string PersonalSkype_Display {
            get {
                return ResourceManager.GetString("PersonalSkype_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Company Salary.
        /// </summary>
        public static string PrevCompanySalary_Display {
            get {
                return ResourceManager.GetString("PrevCompanySalary_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Company Salary must be integer..
        /// </summary>
        public static string PrevCompanySalary_ValidInteger {
            get {
                return ResourceManager.GetString("PrevCompanySalary_ValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string ProfileImage_Display {
            get {
                return ResourceManager.GetString("ProfileImage_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Person-1 Name.
        /// </summary>
        public static string Reference1_Display {
            get {
                return ResourceManager.GetString("Reference1_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Person-1 No..
        /// </summary>
        public static string Reference1No_Display {
            get {
                return ResourceManager.GetString("Reference1No_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Person-2 Name.
        /// </summary>
        public static string Reference2_Display {
            get {
                return ResourceManager.GetString("Reference2_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Person-2 No..
        /// </summary>
        public static string Reference2No_Display {
            get {
                return ResourceManager.GetString("Reference2No_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relieving Date.
        /// </summary>
        public static string RelievingDate_Display {
            get {
                return ResourceManager.GetString("RelievingDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resignation Date.
        /// </summary>
        public static string ResignDate_Display {
            get {
                return ResourceManager.GetString("ResignDate_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resignation Reason.
        /// </summary>
        public static string ResignReason_Display {
            get {
                return ResourceManager.GetString("ResignReason_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string RoleAdmin {
            get {
                return ResourceManager.GetString("RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDM.
        /// </summary>
        public static string RoleBDM {
            get {
                return ResourceManager.GetString("RoleBDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.
        /// </summary>
        public static string RoleDev {
            get {
                return ResourceManager.GetString("RoleDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string RoleHR {
            get {
                return ResourceManager.GetString("RoleHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string RolePM {
            get {
                return ResourceManager.GetString("RolePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin.
        /// </summary>
        public static string RoleSuperAdmin {
            get {
                return ResourceManager.GetString("RoleSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired at Salary.
        /// </summary>
        public static string SalaryHiredAt_Display {
            get {
                return ResourceManager.GetString("SalaryHiredAt_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired at Salary must be integer..
        /// </summary>
        public static string SalaryHiredAt_ValidInteger {
            get {
                return ResourceManager.GetString("SalaryHiredAt_ValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@webastral.com.
        /// </summary>
        public static string SuperAdminEmailID {
            get {
                return ResourceManager.GetString("SuperAdminEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string SuperAdminFullName {
            get {
                return ResourceManager.GetString("SuperAdminFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin123@.
        /// </summary>
        public static string SuperAdminPassword {
            get {
                return ResourceManager.GetString("SuperAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Previous Experience.
        /// </summary>
        public static string TotalPrevExperience_Display {
            get {
                return ResourceManager.GetString("TotalPrevExperience_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Previous Experience must be integer..
        /// </summary>
        public static string TotalPrevExperience_ValidInteger {
            get {
                return ResourceManager.GetString("TotalPrevExperience_ValidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Photo is too large, maximum allowed size is :.
        /// </summary>
        public static string UploadPhotoLength_Invalid {
            get {
                return ResourceManager.GetString("UploadPhotoLength_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload Your Photo of type:.
        /// </summary>
        public static string UploadPhotoType_Invalid {
            get {
                return ResourceManager.GetString("UploadPhotoType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @webastral.com.
        /// </summary>
        public static string ValidDomain {
            get {
                return ResourceManager.GetString("ValidDomain", resourceCulture);
            }
        }
    }
}
